# Generated by Django 3.1.2 on 2020-10-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_student_registration_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='registration_no',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('CSE', 'Computer Science'), ('ETC', 'Electronics & Telecommunications'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering')], default=('IT', 'Information Technology'), max_length=3),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_no',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('I', 'First'), ('II', 'Second'), ('III', 'Third'), ('IV', 'Fourth')], default=('I', 'First'), max_length=3),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='branch',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('CSE', 'Computer Science'), ('ETC', 'Electronics & Telecommunications'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering')], default=('IT', 'Information Technology'), max_length=3),
        ),
    ]
